# Generated by Django 3.2.13 on 2022-06-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='fname',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lname',
            new_name='last',
        ),
    ]
