# Generated by Django 3.2.13 on 2022-06-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='proimg')),
                ('price', models.FloatField()),
                ('review', models.TextField()),
            ],
        ),
    ]
