# Generated by Django 3.2.13 on 2022-06-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro',
            old_name='description',
            new_name='des',
        ),
    ]
