# Generated by Django 3.2.13 on 2022-06-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_description_pro_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='pro',
            name='img',
            field=models.ImageField(upload_to='app1/proimg'),
        ),
    ]
