# Generated by Django 3.2.13 on 2022-07-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220709_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Vendor',
        ),
    ]
